apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-lightning-dev
  labels:
    app: django-lightning-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-lightning-dev
  template:
    metadata:
      labels:
        app: django-lightning-dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
      - name: api
        image: django-lightning:v1.0.0
        imagePullPolicy: Never
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        command: ["uv", "run", "manage.py", "runbolt", "--host", "0.0.0.0", "--port", "8000", "--dev"]
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "1"
        - name: ALLOWED_HOSTS
          value: "*"
        envFrom:
        - configMapRef:
            name: django-lightning-config
        - secretRef:
            name: django-lightning-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}
