# Kube-Linter configuration for django-lightning Kubernetes manifests
checks:
  addAllBuiltIn: true
  doNotInclude:
    - no-read-only-root-fs
    - latest-tag
    - env-var-secret
    - no-anti-affinity
    - unset-memory-requirements
