# Generated by Django 6.0.7 on 2026-07-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_example_concurrent_idx_and_async_trigger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_created_at_idx",
        ),
        migrations.AlterField(
            model_name="asyncmigration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("DEFERRED", "Deferred"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
