# Generated by Django 6.0.7 on 2026-07-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_organization_alter_asyncmigration_options_apikey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("MEMBER", "Member")],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="organizationmember",
            name="org_member_user_idx",
        ),
        migrations.AlterModelOptions(
            name="asyncmigration",
            options={"ordering": ["id"]},
        ),
        migrations.RenameModel(
            old_name="Organization",
            new_name="Tenant",
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="members", to="app.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="organizationmember",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organizationmember",
            name="user",
        ),
        migrations.AddIndex(
            model_name="tenantmember",
            index=models.Index(fields=["tenant", "user"], name="tenant_member_user_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmember",
            unique_together={("tenant", "user")},
        ),
        migrations.DeleteModel(
            name="OrganizationMember",
        ),
    ]
