# Generated by Django 6.0.7 on 2026-08-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tenantmember_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantmember',
            name='tenant_member_user_idx',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='asyncmigration',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='user_unique_email_when_set'),
        ),
    ]
