from collections.abc import Awaitable, Callable
from typing import Any

def is_rust_available() -> bool: ...
def get_rust_core_version() -> str | None: ...
def native_async[**P, R](func: Callable[P, R]) -> Callable[P, Awaitable[R]]: ...
def native_json[In, Out](
    rust_func: Callable[[bytes], bytes] | None,
    response_type: type[Out],
    fallback: Callable[[In], Out] | Callable[[In], Awaitable[Out]] | None = ...,
) -> Callable[[In], Awaitable[Out]]: ...
async def run_native[R](func: Callable[..., R], *args: Any, **kwargs: Any) -> R: ...
