from collections.abc import Callable
from typing import Any

def is_rust_available() -> bool: ...
def get_rust_core_version() -> str | None: ...
async def run_native[R](func: Callable[..., R], *args: Any, **kwargs: Any) -> R: ...
