from collections.abc import Awaitable, Callable
from typing import Any, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")
T = TypeVar("T")

def is_rust_available() -> bool: ...
def get_rust_core_version() -> str | None: ...
def native_async(func: Callable[P, R]) -> Callable[P, Awaitable[R]]: ...
async def run_native(func: Callable[..., R], *args: Any, **kwargs: Any) -> R: ...
async def run_native_json(
    native_func: Callable[[bytes], bytes], payload: Any, response_type: type[T]
) -> T: ...
