//! Native PyO3 FFI Binding for Django-Lightning (`rust_core`).
//!
//! Delegates function execution to workspace domain crates (`db_engine`, `core_utils`, etc.).

use pyo3::prelude::*;
use pyo3::types::PyBytes;

#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

/// Returns the version string of the compiled native Rust core crate.
#[pyfunction]
fn rust_core_version() -> PyResult<&'static str> {
    Ok(env!("CARGO_PKG_VERSION"))
}

/// Helper for ultra-fast, zero-copy memory transfer using raw byte slices (`&[u8]`).
#[pyfunction]
fn process_raw_bytes<'py>(py: Python<'py>, input_bytes: &[u8]) -> PyResult<Bound<'py, PyBytes>> {
    let result_vec = py.detach(|| core_utils::process_raw_bytes_impl(input_bytes));
    Ok(PyBytes::new(py, &result_vec))
}

/// Native SQL query handler delegating execution to the `db_engine` workspace crate.
#[pyfunction]
fn db_query_users_json<'py>(
    py: Python<'py>,
    db_url: String,
    limit: i64,
) -> PyResult<Bound<'py, PyBytes>> {
    let json_bytes = py
        .detach(|| db_engine::db_query_users_json_impl(&db_url, limit))
        .map_err(pyo3::exceptions::PyValueError::new_err)?;

    Ok(PyBytes::new(py, &json_bytes))
}

/// Generic native fetch: keyset-paginated JSON page for any generated Django model.
///
/// `model` is the lowercase Django model name (e.g. "user", "tenant"). The model
/// registry is auto-generated by `manage.py generate_rust_models`, so every model
/// in the Django app is addressable without writing new Rust code.
#[pyfunction]
#[pyo3(signature = (db_url, model, limit=100, after_id=None))]
fn db_fetch_model_json<'py>(
    py: Python<'py>,
    db_url: String,
    model: String,
    limit: i64,
    after_id: Option<i64>,
) -> PyResult<Bound<'py, PyBytes>> {
    let json_bytes = py
        .detach(|| db_engine::db_fetch_model_json_impl(&db_url, &model, limit, after_id))
        .map_err(pyo3::exceptions::PyValueError::new_err)?;

    Ok(PyBytes::new(py, &json_bytes))
}

/// List all Django model names registered in the native fetch registry.
#[pyfunction]
fn db_registered_models() -> Vec<&'static str> {
    db_engine::queries::MODEL_NAMES.to_vec()
}

#[pymodule]
fn rust_core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(rust_core_version, m)?)?;
    m.add_function(wrap_pyfunction!(process_raw_bytes, m)?)?;
    m.add_function(wrap_pyfunction!(db_query_users_json, m)?)?;
    m.add_function(wrap_pyfunction!(db_fetch_model_json, m)?)?;
    m.add_function(wrap_pyfunction!(db_registered_models, m)?)?;
    Ok(())
}
