"""Django Management Command to generate Rust models matching Django models.

Usage:
    python manage.py generate_rust_models
    python manage.py generate_rust_models --output rust_core/crates/db_engine/src/models.rs
"""

from pathlib import Path
from typing import Any

from django.apps import apps
from django.core.management.base import BaseCommand
from django.db import models

FIELD_TYPE_MAP = {
    models.AutoField: "i64",
    models.BigAutoField: "i64",
    models.SmallIntegerField: "i16",
    models.IntegerField: "i32",
    models.BigIntegerField: "i64",
    models.PositiveIntegerField: "u32",
    models.PositiveSmallIntegerField: "u16",
    models.PositiveBigIntegerField: "u64",
    models.FloatField: "f64",
    models.DecimalField: "f64",
    models.BooleanField: "bool",
    models.NullBooleanField: "Option<bool>",
    models.CharField: "String",
    models.TextField: "String",
    models.SlugField: "String",
    models.EmailField: "String",
    models.URLField: "String",
    models.UUIDField: "String",
    models.DateTimeField: "chrono::DateTime<chrono::Utc>",
    models.DateField: "chrono::NaiveDate",
    models.TimeField: "chrono::NaiveTime",
    models.JSONField: "serde_json::Value",
    models.BinaryField: "Vec<u8>",
}


class Command(BaseCommand):
    help = "Generate Rust struct definitions from Django models for rust_core database interop."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            type=str,
            default="rust_core/crates/db_engine/src/models.rs",
            help="Path to output Rust file (default: rust_core/crates/db_engine/src/models.rs).",
        )
        parser.add_argument(
            "--app",
            type=str,
            default="app",
            help="Django app name to inspect (default: app).",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        output_path = Path(options["output"])
        app_name = options["app"]

        app_config = apps.get_app_config(app_name)
        app_models = app_config.get_models()

        rust_code_lines = [
            "// Auto-generated by `python manage.py generate_rust_models`.",
            "// DO NOT EDIT MANUALLY. Single Source of Truth: Django app models.py",
            "",
            "use serde::{Deserialize, Serialize};",
            "use sqlx::FromRow;",
            "",
        ]

        for model in app_models:
            struct_code = self._generate_struct_for_model(model)
            rust_code_lines.append(struct_code)
            rust_code_lines.append("")

        output_content = "\n".join(rust_code_lines)

        # Ensure parent directories exist
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output_content, encoding="utf-8")

        self.stdout.write(
            self.style.SUCCESS(
                f"[OK] Successfully generated Rust models for app '{app_name}' at '{output_path}'."
            )
        )

    def _generate_struct_for_model(self, model: type[models.Model]) -> str:
        model_name = model.__name__
        struct_name = f"{model_name}Row"
        table_name = model._meta.db_table

        lines = [
            f"/// Generated Rust struct for Django model `{model_name}`.",
            f"/// DB Table: `{table_name}`.",
            "#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]",
            f"pub struct {struct_name} {{",
        ]

        field_names = []
        for field in model._meta.get_fields():
            if not field.concrete or field.many_to_many:
                continue

            col_name = field.column
            field_names.append(col_name)
            rust_type = self._map_field_type(field)

            is_nullable = getattr(field, "null", False)
            if is_nullable and not rust_type.startswith("Option<"):
                rust_type = f"Option<{rust_type}>"

            lines.append(f"    pub {col_name}: {rust_type},")

        lines.append("}")
        lines.append("")

        # Add helper metadata block
        cols_str = ", ".join(f'"{name}"' for name in field_names)
        lines.append(f"impl {struct_name} {{")
        lines.append(f'    pub const TABLE_NAME: &\'static str = "{table_name}";')
        lines.append(f"    pub const COLUMNS: &'static [&'static str] = &[{cols_str}];")
        lines.append("}")

        return "\n".join(lines)

    def _map_field_type(self, field: Any) -> str:
        if isinstance(field, models.ForeignKey) or isinstance(field, models.OneToOneField):
            target_field = field.target_field
            return FIELD_TYPE_MAP.get(type(target_field), "i64")

        field_class = type(field)
        for cls in field_class.__mro__:
            if cls in FIELD_TYPE_MAP:
                return FIELD_TYPE_MAP[cls]

        return "String"
