"""Django Management Command to generate Rust models matching Django models.

Generates two files inside the `db_engine` crate:

- ``models.rs``: one ``#[derive(FromRow, Serialize)]`` struct per Django model,
  with ``TABLE_NAME`` / ``COLUMNS`` / ``PK`` metadata constants. Sensitive columns
  (password hashes, key hashes, secrets, tokens) are excluded from the generated
  structs and column lists entirely, so they are never even fetched from the
  database by native queries, let alone serialized into JSON output.
- ``queries.rs``: a model registry mapping Django model names to typed,
  keyset-paginated native fetch functions, powering the generic
  ``rust_core.db_fetch_model_json`` fast path for every model automatically.

Usage:
    python manage.py generate_rust_models
    python manage.py generate_rust_models --app myapp \
        --output rust_core/crates/db_engine/src/models.rs
"""

from pathlib import Path
from typing import Any

from django.apps import apps
from django.core.management.base import BaseCommand
from django.db import models

# Columns holding secrets/credentials are never mirrored into the Rust layer, so a
# `SELECT`-based helper can't accidentally serialize them back to an API client.
SENSITIVE_COLUMNS = {
    "password",
    "key_hash",
    "secret",
    "secret_key",
    "token",
    "token_hash",
    "api_key",
}

FIELD_TYPE_MAP = {
    models.AutoField: "i64",
    models.BigAutoField: "i64",
    models.SmallIntegerField: "i16",
    models.IntegerField: "i32",
    models.BigIntegerField: "i64",
    # Postgres has no unsigned column types (Django stores these as signed
    # integers with CHECK constraints), so map to portable signed Rust types.
    models.PositiveIntegerField: "i32",
    models.PositiveSmallIntegerField: "i16",
    models.PositiveBigIntegerField: "i64",
    models.FloatField: "f64",
    models.DecimalField: "f64",
    models.BooleanField: "bool",
    models.NullBooleanField: "Option<bool>",
    models.CharField: "String",
    models.TextField: "String",
    models.SlugField: "String",
    models.EmailField: "String",
    models.URLField: "String",
    models.UUIDField: "String",
    models.DateTimeField: "chrono::DateTime<chrono::Utc>",
    models.DateField: "chrono::NaiveDate",
    models.TimeField: "chrono::NaiveTime",
    models.JSONField: "serde_json::Value",
    models.BinaryField: "Vec<u8>",
}

class Command(BaseCommand):
    help = "Generate Rust struct definitions from Django models for rust_core database interop."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            type=str,
            default="rust_core/crates/db_engine/src/models.rs",
            help="Path to output Rust file (default: rust_core/crates/db_engine/src/models.rs).",
        )
        parser.add_argument(
            "--app",
            type=str,
            default="app",
            help="Django app name to inspect (default: app).",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        output_path = Path(options["output"])
        app_name = options["app"]

        app_config = apps.get_app_config(app_name)
        app_models = app_config.get_models()

        rust_code_lines = [
            "// Auto-generated by `python manage.py generate_rust_models`.",
            "// DO NOT EDIT MANUALLY. Single Source of Truth: Django app models.py",
            "",
            "use serde::{Deserialize, Serialize};",
            "use sqlx::FromRow;",
            "",
        ]

        model_list = list(app_models)
        for model in model_list:
            struct_code = self._generate_struct_for_model(model)
            rust_code_lines.append(struct_code)
            rust_code_lines.append("")

        output_content = "\n".join(rust_code_lines)

        # Ensure parent directories exist
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output_content, encoding="utf-8")

        queries_path = output_path.parent / "queries.rs"
        queries_path.write_text(self._generate_queries_registry(model_list), encoding="utf-8")

        self.stdout.write(
            self.style.SUCCESS(
                f"[OK] Successfully generated Rust models for app '{app_name}' at "
                f"'{output_path}' and query registry at '{queries_path}'."
            )
        )

    def _generate_struct_for_model(self, model: type[models.Model]) -> str:
        model_name = model.__name__
        struct_name = f"{model_name}Row"
        table_name = model._meta.db_table

        lines = [
            f"/// Generated Rust struct for Django model `{model_name}`.",
            f"/// DB Table: `{table_name}`.",
            "#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]",
            f"pub struct {struct_name} {{",
        ]

        field_names = []
        for field in model._meta.get_fields():
            if not field.concrete or field.many_to_many:
                continue

            col_name = field.column
            if col_name in SENSITIVE_COLUMNS:
                continue
            field_names.append(col_name)
            rust_type = self._map_field_type(field)

            is_nullable = getattr(field, "null", False)
            if is_nullable and not rust_type.startswith("Option<"):
                rust_type = f"Option<{rust_type}>"

            lines.append(f"    pub {col_name}: {rust_type},")

        lines.append("}")
        lines.append("")

        # Add helper metadata block
        pk_column = model._meta.pk.column
        cols_str = ", ".join(f'"{name}"' for name in field_names)
        lines.append(f"impl {struct_name} {{")
        lines.append(f'    pub const TABLE_NAME: &\'static str = "{table_name}";')
        lines.append(f"    pub const COLUMNS: &'static [&'static str] = &[{cols_str}];")
        lines.append(f'    pub const PK: &\'static str = "{pk_column}";')
        lines.append("}")

        return "\n".join(lines)

    def _generate_queries_registry(self, model_list: list[type[models.Model]]) -> str:
        """Generate queries.rs: a registry dispatching model names to typed fetches."""
        model_names = [model._meta.model_name for model in model_list]
        names_str = ", ".join(f'"{name}"' for name in model_names)

        lines = [
            "// Auto-generated by `python manage.py generate_rust_models`.",
            "// DO NOT EDIT MANUALLY. Single Source of Truth: Django app models.py",
            "",
            "use crate::models::*;",
            "use crate::{fetch_page_json, DbPool};",
            "",
            "/// All Django model names addressable by the native fetch registry.",
            f"pub const MODEL_NAMES: &[&str] = &[{names_str}];",
            "",
            "/// Fetch a keyset-paginated JSON page for any registered Django model.",
            "pub async fn fetch_model_page_json(",
            "    pool: &DbPool,",
            "    model: &str,",
            "    limit: i64,",
            "    after_id: Option<i64>,",
            ") -> Result<Vec<u8>, String> {",
            "    match model {",
        ]

        for model in model_list:
            struct_name = f"{model.__name__}Row"
            model_name = model._meta.model_name
            lines.append(f'        "{model_name}" => {{')
            lines.append(f"            fetch_page_json::<{struct_name}>(")
            lines.append("                pool,")
            lines.append(f"                {struct_name}::TABLE_NAME,")
            lines.append(f"                {struct_name}::COLUMNS,")
            lines.append(f"                {struct_name}::PK,")
            lines.append("                limit,")
            lines.append("                after_id,")
            lines.append("            )")
            lines.append("            .await")
            lines.append("        }")

        lines.extend(
            [
                "        _ => Err(format!(",
                '            "Unknown model \'{model}\'. Known models: {MODEL_NAMES:?}. \\',
                '             Re-run `manage.py generate_rust_models` after adding models."',
                "        )),",
                "    }",
                "}",
                "",
            ]
        )

        return "\n".join(lines)

    def _map_field_type(self, field: Any) -> str:
        if isinstance(field, models.ForeignKey) or isinstance(field, models.OneToOneField):
            target_field = field.target_field
            return FIELD_TYPE_MAP.get(type(target_field), "i64")

        field_class = type(field)
        for cls in field_class.__mro__:
            if cls in FIELD_TYPE_MAP:
                return FIELD_TYPE_MAP[cls]

        return "String"
