// Auto-generated by `python manage.py generate_rust_models`.
// DO NOT EDIT MANUALLY. Single Source of Truth: Django app models.py

use serde::{Deserialize, Serialize};
use sqlx::FromRow;

/// Generated Rust struct for Django model `User`.
/// DB Table: `app_user`.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct UserRow {
    pub id: i64,
    pub password: String,
    pub last_login: Option<chrono::DateTime<chrono::Utc>>,
    pub is_superuser: bool,
    pub username: String,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub is_staff: bool,
    pub is_active: bool,
    pub date_joined: chrono::DateTime<chrono::Utc>,
    pub bio: String,
    pub avatar_url: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl UserRow {
    pub const TABLE_NAME: &'static str = "app_user";
    pub const COLUMNS: &'static [&'static str] = &["id", "password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined", "bio", "avatar_url", "created_at", "updated_at"];
}

/// Generated Rust struct for Django model `AsyncMigration`.
/// DB Table: `app_asyncmigration`.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AsyncMigrationRow {
    pub id: i64,
    pub name: String,
    pub status: String,
    pub batch_size: u32,
    pub processed_count: u32,
    pub total_count: u32,
    pub error_message: String,
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl AsyncMigrationRow {
    pub const TABLE_NAME: &'static str = "app_asyncmigration";
    pub const COLUMNS: &'static [&'static str] = &["id", "name", "status", "batch_size", "processed_count", "total_count", "error_message", "started_at", "completed_at", "created_at", "updated_at"];
}
