// Auto-generated by `python manage.py generate_rust_models`.
// DO NOT EDIT MANUALLY. Single Source of Truth: Django app models.py

use crate::models::*;
use crate::{fetch_page_json, DbPool};

/// All Django model names addressable by the native fetch registry.
pub const MODEL_NAMES: &[&str] = &["user", "asyncmigration", "tenant", "tenantmember", "apikey"];

/// Fetch a keyset-paginated JSON page for any registered Django model.
pub async fn fetch_model_page_json(
    pool: &DbPool,
    model: &str,
    limit: i64,
    after_id: Option<i64>,
) -> Result<Vec<u8>, String> {
    match model {
        "user" => {
            fetch_page_json::<UserRow>(
                pool,
                UserRow::TABLE_NAME,
                UserRow::COLUMNS,
                UserRow::PK,
                limit,
                after_id,
            )
            .await
        }
        "asyncmigration" => {
            fetch_page_json::<AsyncMigrationRow>(
                pool,
                AsyncMigrationRow::TABLE_NAME,
                AsyncMigrationRow::COLUMNS,
                AsyncMigrationRow::PK,
                limit,
                after_id,
            )
            .await
        }
        "tenant" => {
            fetch_page_json::<TenantRow>(
                pool,
                TenantRow::TABLE_NAME,
                TenantRow::COLUMNS,
                TenantRow::PK,
                limit,
                after_id,
            )
            .await
        }
        "tenantmember" => {
            fetch_page_json::<TenantMemberRow>(
                pool,
                TenantMemberRow::TABLE_NAME,
                TenantMemberRow::COLUMNS,
                TenantMemberRow::PK,
                limit,
                after_id,
            )
            .await
        }
        "apikey" => {
            fetch_page_json::<APIKeyRow>(
                pool,
                APIKeyRow::TABLE_NAME,
                APIKeyRow::COLUMNS,
                APIKeyRow::PK,
                limit,
                after_id,
            )
            .await
        }
        _ => Err(format!(
            "Unknown model '{model}'. Known models: {MODEL_NAMES:?}. \
             Re-run `manage.py generate_rust_models` after adding models."
        )),
    }
}
